name: Docker Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ethanscully
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build Image
        run: |
          docker build \
          -t ethanscully/warp:latest \
          -t ethanscully/warp:${GITHUB_REF_NAME#v} .
          docker push ethanscully/warp:latest
          docker push ethanscully/warp:${GITHUB_REF_NAME#v}
